### Menu Index
GET http://localhost:3000/api/menu

### Shows Item 
GET http://localhost:3000/api/menu/1

### unsuccesfully shows item 
GET http://localhost:3000/api/menu/1000

### successfuly update item 
PUT http://localhost:3000/api/menu/1
Content-Type: application/json

{
    "name": "Test123"
}

### Deletes menu item 
DELETE http://localhost:3000/api/menu/2

### Unsuccessfuly deletes joke 
DELETE http://localhost:3000/api/menu/20000

### successfully creates item 
POST http://localhost:3000/api/menu
Content-Type: application/json

{
    "name": "Test juice",
    "category_id": 1
}

### unsuccessfully creates item 
POST http://localhost:3000/api/menu
Content-Type: application/json

{
    "name": "whatever juice"
}


### create user 
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "first_name": "Chelsey",
    "last_name": "Bennett",
    "email": "test@b.com",
    "phone_number": "0408285129",
    "password": "password3",
    "password_confirmation": "password3"

}
### Successfully sign_in 
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json
{
    "email": "test@a.com",
    "password": "password2"
}




